# Generated by Django 6.0.4 on 2026-04-25 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_score_gamesession_score_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='student_user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='badges',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('froggy', 'Froggy Jumps'), ('match', 'Match'), ('memory', 'Memory'), ('fill_blank', 'Fill in the Blank'), ('quiz', 'Quiz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='score_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='time_seconds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='xp_earned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
